version: "3.9"

services:
  api:
    build:
      context: .
      dockerfile: API/Dockerfile
    ports:
      - "81:80"
    environment:
      - RMQ_HOST=rmq
      - RMQ_USERNAME=application
      - RMQ_PASSWORD=pepsi

  web:
    build:
      context: Web
      dockerfile: Dockerfile
    ports:
      - "80:80"
    environment:
      - API_URL=http://api:80
      
  seq:
    image: datalust/seq
    ports:
      - "5341:5341"
      - "5342:80"
    volumes:
      - rps_seq_data1:/data
    environment:
      - ACCEPT_EULA=Y
        
  zipkin:
    image: openzipkin/zipkin
    ports:
      - "9411:9411"
    environment:
      - STORAGE_TYPE=mysql
      - MYSQL_HOST=zipkin-storage
      - MYSQL_USER=zipkin
      - MYSQL_PASS=zipkin
    depends_on:
      - zipkin-storage
  
  zipkin-storage:
    image: openzipkin/zipkin-mysql
    ports:
      - 3306:3306
    volumes:
      - zipkin_data:/mysql/data
        
volumes:
  rps_seq_data1:     
  zipkin_data: